### ISSUE TITLE
Tables sometimes do not show up 

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#167]
**Describe the bug**
After validation and simulation, tables does not show up sometime. 

**To Reproduce**
1. Select a CSV file
2. Click "Validate" or "Simulate"
3. Wait
4. See if tables are displayed

**Expected behavior**
Tables are always displayed.

**Screenshots**
![Screenshot 2023-12-22 at 16 57 52](https://github.com/monodera/pfs_target_uploader/assets/90394/facf667f-cd6c-4dc0-a38c-f45a3c556fb9)

**Additional context**
Sometimes, I saw the following error message. Looks like updating `value` object in Tabulator widgets are not behaving nicely.

```
Traceback (most recent call last):
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 286, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 245, in handle_event
    event_cls._handle_event(doc, event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 280, in _handle_event
    cb(event.msg_data)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 494, in _server_event
    self._comm_event(doc, event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 481, in _comm_event
    state._handle_exception(e)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/state.py", line 442, in _handle_exception
    raise exception
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 479, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 416, in _process_bokeh_event
    self._process_event(event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/button.py", line 247, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameters.py", line 542, in __set__
    super().__set__(obj,val)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/work/monodera/dev/pfs_target_uploader/src/pfs_target_uploader/pn_app.py", line 165, in cb_validate
    panel_targets.show_results(df_validated)
  File "/work/monodera/dev/pfs_target_uploader/src/pfs_target_uploader/widgets/TargetWidgets.py", line 34, in show_results
    self.table_all.value = pd.DataFrame()
    ^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line 1550, in _update_cds
    self._update_selected()
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line 1572, in _update_selected
    index = self.value.iloc[self.selection].index
            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/pandas/core/indexing.py", line 1705, in _getitem_axis
    return self._get_list_axis(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/pandas/core/indexing.py", line 1679, in _get_list_axis
    raise IndexError("positional indexers are out-of-bounds") from err
IndexError: positional indexers are out-of-bounds
```

**Comment by monodera** [comment]
It looks like that replacing `pn.Tabulator().value` by an empty DataFrame would not work. Instead, `pn.Tabulator().value[0:0]` clears the DataFrame and works as expected (though I'm not 100% sure).
