### ISSUE TITLE
error when clicking ppc id in the admin page

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#177]
**Describe the bug**
When I click a PPC ID in the admin page, it raises an error.

**To Reproduce**
1. Go to the admin page
2. Click on the magnifier icon on the right
3. Move to the "PPC details" tab
4. Click a PPC ID (e.g, Point_low_1) in the list
5. see the error in the following

```
2024-01-03 21:41:29,071 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'cell-click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p4174'}], ['column', 'ppc_code'], ['row', 0]]}}}]}
 error: ValueError('The Tabulator widget expects the provided `value` Pandas DataFrame to have unique indexes, in particular when it has to deal with click or edit events. Found this duplicate index: 0')
Traceback (most recent call last):
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 286, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 245, in handle_event
    event_cls._handle_event(doc, event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 280, in _handle_event
    cb(event.msg_data)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 494, in _server_event
    self._comm_event(doc, event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 481, in _comm_event
    state._handle_exception(e)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/state.py", line 442, in _handle_exception
    raise exception
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 479, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 416, in _process_bokeh_event
    self._process_event(event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line 1260, in _process_event
    self._validate_iloc(idx, iloc)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line 1225, in _validate_iloc
    raise ValueError(
ValueError: The Tabulator widget expects the provided `value` Pandas DataFrame to have unique indexes, in particular when it has to deal with click or edit events. Found this duplicate index: 0
```

**Expected behavior**
No error message

**Comment by monodera** [comment]
I think it is fixed in #183 and merged to #dev-main branch
