### ISSUE TITLE
The online PPP cannot finish by failing to show plots under some conditions

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#212]
**Describe the bug**
In some cases, the online PPP fails to finish. As long as I tried with various cases, it seems to fail to show plots. Success/fail cases are as follows:

- Success
  - Firefox from Office
  - Chrome from Office, Home
  - localhost without Nginx reverse proxy
  - Firefox from a virtual machine in Parallels on macOS

- Fail
  - Firefox from Home
  - Safari from Home
  - Firefox from Home via a commercial VPN (NordVPN)

Here is a CSV file to reproduce the issue. There are 4000 objects at random coordinates either `L` or `M` resolution.

[random_example_n00004000_lm.csv](https://github.com/user-attachments/files/15572297/random_example_n00004000_lm.csv)

It seems that the websocket over reverse proxy is likely the cause, but I haven't yet found the exact cause.

**To Reproduce**
1. Open the web app.
2. Select the CSV file attached above.
3. Click "Simulate".
4. Wait to see if the calculation finishes in 5-10min.

**Expected behavior**
Show the results in the right panel.

**Computer Environment:**
 - OS: macOS
 - Browser: Chrome, Safari, Firefox]

**Comment by monodera** [comment]
In some cases, the app output error message:

```
2024-05-31T10:23:51.209674-10:00 pfs-etc pfs-uploader-dev[222989]: 2024-05-31 10:23:51.209 | INFO     | pfs_target_uploader.utils.ppp:netflow_iter:885 - PPP stopped since Nppc > 200 [netflow_iter s2]
2024-05-31T10:23:53.910171-10:00 pfs-etc pfs-uploader-dev[222989]: 2024-05-31 10:23:53.909 | INFO     | pfs_target_uploader.utils.ppp:PPPrunStart:991 - PPP run finished in 490.4 seconds
2024-05-31T10:23:53.910607-10:00 pfs-etc pfs-uploader-dev[222989]: 2024-05-31 10:23:53.910 | INFO     | pfs_target_uploader.utils.ppp:PPPrunStart:992 - PPP running status: 999
2024-05-31T10:23:53.913352-10:00 pfs-etc pfs-uploader-dev[222989]: 2024-05-31 10:23:53.913 | INFO     | pfs_target_uploader.utils.ppp:ppp_result:1372 - start creating PPP figures
2024-05-31T10:23:55.121753-10:00 pfs-etc pfs-uploader-dev[222989]: 2024-05-31 10:23:55.121 | INFO     | pfs_target_uploader.utils.ppp:ppp_result:1454 - creating PPP figures finished
2024-05-31T10:23:55.122182-10:00 pfs-etc pfs-uploader-dev[222989]: 2024-05-31 10:23:55.121 | INFO     | pfs_target_uploader.widgets.PppResultWidgets:show_results:92 - showing PPP results
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]: ERROR:bokeh.server.protocol_handler:error handling message
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]: message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1076'}]]}}}]}
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]: error: WebSocketClosedError()
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]: Traceback (most recent call last):
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:    work = await handler(message, connection)
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:    result = func(self, *args, **kwargs)
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 286, in _handle_patch
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:    message.apply_to_document(self.document, self)
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:    return f()
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:           ^^^
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/document.py", line 391, in apply_json_patch
2024-05-31T10:23:55.188022-10:00 pfs-etc pfs-uploader-dev[222989]:    DocumentPatchedEvent.handle_event(self, event, setter)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 245, in handle_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    event_cls._handle_event(doc, event)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 280, in _handle_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    cb(event.msg_data)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    model._trigger_event(event)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    invoke_with_curdoc(doc, callback_invoker)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    return f()
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:           ^^^
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    cast(EventCallbackWithEvent, callback)(event)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 494, in _server_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    self._comm_event(doc, event)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 481, in _comm_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    state._handle_exception(e)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/state.py", line 442, in _handle_exception
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    raise exception
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 479, in _comm_event
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:    self._process_bokeh_event(doc, event)
2024-05-31T10:23:55.188665-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 416, in _process_bokeh_event
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    self._process_event(event)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/button.py", line 247, in _process_event
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    self.clicks += 1
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    ^^^^^^^^^^^
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 528, in _f
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    instance_param.__set__(obj, val)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 530, in _f
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    return f(self, obj, val)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:           ^^^^^^^^^^^^^^^^^
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameters.py", line 543, in __set__
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    super().__set__(obj,val)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 530, in _f
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    return f(self, obj, val)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:           ^^^^^^^^^^^^^^^^^
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 1552, in __set__
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    obj.param._call_watcher(watcher, event)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2525, in _call_watcher
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    self_._execute_watcher(watcher, (event,))
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2505, in _execute_watcher
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    watcher.fn(*args, **kwargs)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/src/pfs_target_uploader/pn_app.py", line 266, in cb_PPP
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    panel_ppp.show_results()
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/src/pfs_target_uploader/widgets/PppResultWidgets.py", line 212, in show_results
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    self.ppp_figure.append(self.ppp_alert)
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/layout/base.py", line 450, in append
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    self.objects = new_objects
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    ^^^^^^^^^^^^
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 528, in _f
2024-05-31T10:23:55.189159-10:00 pfs-etc pfs-uploader-dev[222989]:    instance_param.__set__(obj, val)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 530, in _f
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    return f(self, obj, val)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:           ^^^^^^^^^^^^^^^^^
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 1552, in __set__
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    obj.param._call_watcher(watcher, event)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2525, in _call_watcher
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    self_._execute_watcher(watcher, (event,))
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2505, in _execute_watcher
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    watcher.fn(*args, **kwargs)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 374, in _param_change
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    self._apply_update(named_events, properties, model, ref)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 301, in _apply_update
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    with unlocked():
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/home/monodera/.pyenv/versions/3.11.9/lib/python3.11/contextlib.py", line 144, in __exit__
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    next(self.gen)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/document.py", line 327, in unlocked
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    futures += dispatch_tornado(conn, dispatch_events)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/document.py", line 252, in dispatch_tornado
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    WebSocketHandler.write_message(socket, msg.content_json)
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py", line 332, in write_message
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]:    raise WebSocketClosedError()
2024-05-31T10:23:55.189708-10:00 pfs-etc pfs-uploader-dev[222989]: tornado.websocket.WebSocketClosedError
2024-05-31T10:23:55.190221-10:00 pfs-etc pfs-uploader-dev[222989]: WARNING:bokeh.server.views.ws:Failed sending message as connection was closed
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]: ERROR:asyncio:Task exception was never retrieved
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]: future: <Task finished name='Task-929' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py:1086> exception=WebSocketClosedError()>
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]: Traceback (most recent call last):
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py", line 1088, in wrapper
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]:    await fut
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]: tornado.iostream.StreamClosedError: Stream is closed
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]: During handling of the above exception, another exception occurred:
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]: Traceback (most recent call last):
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]:  File "/work/monodera/dev/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py", line 1090, in wrapper
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]:    raise WebSocketClosedError()
2024-05-31T10:23:55.190726-10:00 pfs-etc pfs-uploader-dev[222989]: tornado.websocket.WebSocketClosedError
```
