### ISSUE TITLE
KeyError at some point

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#41]
**Describe the bug**
`KeyError` happens and it seems to freeze the app.

**To Reproduce**
I don't know. Need to be explored.

**Expected behavior**
No error.

**Additional context**
I found the following lines in a log file.

```
[I 231004 15:45:11 pn_app:40] S24B-QN009.csv is selected.
[I 231004 15:45:11 utils:392] [STAGE 1] Checking column names
[I 231004 15:45:11 utils:209] Required key `obj_id` is found
[I 231004 15:45:11 utils:209] Required key `ob_code` is found
[I 231004 15:45:11 utils:209] Required key `ra` is found
[I 231004 15:45:11 utils:209] Required key `dec` is found
[I 231004 15:45:11 utils:209] Required key `equinox` is found
[I 231004 15:45:11 utils:209] Required key `priority` is found
[I 231004 15:45:11 utils:209] Required key `exptime` is found
[I 231004 15:45:11 utils:209] Required key `resolution` is found
[W 231004 15:45:11 utils:226] Optional key `pmra` is missing
[W 231004 15:45:11 utils:226] Optional key `pmdec` is missing
[W 231004 15:45:11 utils:226] Optional key `parallax` is missing
[W 231004 15:45:11 utils:226] Optional key `tract` is missing
[W 231004 15:45:11 utils:226] Optional key `patch` is missing
[W 231004 15:45:11 utils:226] Optional key `filter_g` is missing
[W 231004 15:45:11 utils:226] Optional key `filter_r` is missing
[W 231004 15:45:11 utils:226] Optional key `filter_i` is missing
[W 231004 15:45:11 utils:226] Optional key `filter_z` is missing
[W 231004 15:45:11 utils:226] Optional key `filter_y` is missing
[W 231004 15:45:11 utils:226] Optional key `filter_j` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_g` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_r` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_i` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_z` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_y` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_j` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_error_g` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_error_r` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_error_i` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_error_z` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_error_y` is missing
[W 231004 15:45:11 utils:226] Optional key `flux_error_j` is missing
[I 231004 15:45:11 utils:394] [STAGE 1] required_keys status: True (Success if True)
[I 231004 15:45:11 utils:397] [STAGE 1] optional_keys status: True (Success if True)
[I 231004 15:45:11 utils:410] [STAGE 2] Checking string values
[I 231004 15:45:11 utils:412] [STAGE 2] status: True (Success if True)
[I 231004 15:45:11 utils:420] [STAGE 3] Checking wheter values are in allowed ranges
[I 231004 15:45:11 utils:422] [STAGE 3] status: True (Success if True)
[I 231004 15:45:11 utils:429] [STAGE 4] Checking whether all ob_code are unique
[I 231004 15:45:11 utils:372] All 'ob_code' are unique.
[I 231004 15:45:11 utils:431] [STAGE 4] status: True (Success if True)
2023-10-04 15:45:11,435 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type
': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p2194'}]]}}}]}
 error: KeyError('priority')
Traceback (most recent call last):
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 286, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_
doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py",
line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_
doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/document.py", l
ine 391, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", lin
e 245, in handle_event
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", lin
e 280, in _handle_event
    cb(event.msg_data)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py",
line 390, in trigger_event
    model._trigger_event(event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py
", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py",
line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py",
line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py
", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 491,
in _server_event
    self._comm_event(doc, event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 478,
in _comm_event
    state._handle_exception(e)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/state.py", line 436,
in _handle_exception
    raise exception
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 476,
in _comm_event
    self._process_bokeh_event(doc, event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 413,
in _process_bokeh_event
    self._process_event(event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/button.py", line
 243, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
367, in _f
    instance_param.__set__(obj, val)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/__init__.py", line 625,
in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/work/monodera/gh/monodera/pfs_target_uploader/src/pfs_target_uploader/pn_app.py", line 167, in cb_validate
    panel_targets.show_results(df_input)
  File "/work/monodera/gh/monodera/pfs_target_uploader/src/pfs_target_uploader/widgets.py", line 335, in show_results
    self.table_all.value = pd.DataFrame()
    ^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
367, in _f
    instance_param.__set__(obj, val)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line
2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line
 1494, in _update_cds
    super()._update_cds(*events)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/util/__init__.py", line
391, in wrapped
    fn(self, *args, **kwargs)
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line
 277, in _update_cds
    self._processed, data = self._get_data()
                            ^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line
 1294, in _get_data
    df = self._sort_df(df)
         ^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/tables.py", line
 375, in _sort_df
    df_sorted = df.sort_values(fields, ascending=ascending, kind='mergesort',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 69
30, in sort_values
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 69
30, in <listcomp>
    keys = [self._get_label_or_level_values(x, axis=axis) for x in by]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/gh/monodera/pfs_target_uploader/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line
1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'priority'
```

**Comment by monodera** [comment]
I think it's fixed. Let's file another ticket if the issue persists.
