### ISSUE TITLE
PPP calculation does not return for a catalog with ~1000 objects

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#75]
I used a catalog containing 100 objects with random positions at -30<dec<85 and online PPP won't return and eventually the connection is closed. I'm wondering if it's due to the catalog, PPP, Panel app (bokeh server), or Nginx.

[random_example_n00100.csv](https://github.com/monodera/pfs_target_uploader/files/13067758/random_example_n00100.csv)

**Comment by monodera** [comment]
Perhaps due to the changes in #119 and #120, the issue seems to be fixed. I successfully finished and saw plots for 1000 random sample asking 1hr integration. I'll close this issue for now.

**Comment by monodera** [comment]
With 1000 random points with 1hr exposure, Firefox and Safari got disconnected, while Chrome accepts the figures.

**Comment by monodera** [comment]
tornado websocket error occured for 10000 objects with 1hr exposure time (4 pointings, >~30000 polygons) on my local computer (without nginx proxy). I guess this is a limit imposed by tornado.

```
[I 231101 12:12:17 ppp:914] PPP run finished in 12756.2 seconds
[I 231101 12:12:17 ppp:1280] start creating PPP figures
[I 231101 12:12:44 ppp:1357] creating PPP figures finished
[I 231101 12:12:44 PppResultWidgets:73] showing PPP results
2023-11-01 12:12:44,756 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1060'}]]}}}]}
 error: WebSocketClosedError()
Traceback (most recent call last):
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 286, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 245, in handle_event
    event_cls._handle_event(doc, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 280, in _handle_event
    cb(event.msg_data)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 494, in _server_event
    self._comm_event(doc, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 481, in _comm_event
    state._handle_exception(e)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/state.py", line 441, in _handle_exception
    raise exception
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 479, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 416, in _process_bokeh_event
    self._process_event(event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/button.py", line 247, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameters.py", line 542, in __set__
    super().__set__(obj,val)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/src/pfs_target_uploader/pn_app.py", line 229, in cb_PPP
    panel_ppp.show_results()
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/src/pfs_target_uploader/widgets/PppResultWidgets.py", line 187, in show_results
    self.ppp_figure.append(self.ppp_alert)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/layout/base.py", line 446, in append
    self.objects = new_objects
    ^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 374, in _param_change
    self._apply_update(named_events, properties, model, ref)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 301, in _apply_update
    with unlocked():
  File "/Users/monodera/.pyenv/versions/3.11.6/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/document.py", line 268, in unlocked
    futures += dispatch_tornado(conn, dispatch_events)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/document.py", line 193, in dispatch_tornado
    WebSocketHandler.write_message(socket, msg.metadata_json),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py", line 331, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2023-11-01 12:12:44,770 Failed sending message as connection was closed
2023-11-01 12:12:44,770 Task exception was never retrieved
future: <Task finished name='Task-60979' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py:1085> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py", line 1087, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/tornado/websocket.py", line 1089, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2023-11-01 12:12:44,770 WebSocket connection closed: code=None, reason=None
[I 231101 12:12:44 pn_app:37] config params from dotenv: OrderedDict([('OUTPUT_DIR', 'data')])
[I 231101 12:12:44 pn_app:40] data already exists.
2023-11-01 12:12:46,261 WebSocket connection opened
2023-11-01 12:12:46,264 ServerConnection created
```

**Comment by monodera** [comment]
Chrome seems ok with 2000 random objects (4910 pointings returned)

**Comment by wanqqq31** [comment]
This problem should be solved by u/wanqqq/PPP-exetime branch. Now PPP stops if 1) the running time exceeds 15min, and 2) the allocated N_ppc in each resolution mode exceeds 200. I suspect 200 Nppc is enough for showing the results since it already exceeds the upper limit of normal program. But please let me know if we need to show more.

**Comment by monodera** [comment]
I guess those who plan an intensive program would need more pointings, but let's postpone digging further into this issue.
