### ISSUE TITLE
PPP crashes with >3999 pointings

### ISSUE THREAD

**Issue by monodera** [monodera/pfs_target_uploader#79]
**Describe the bug**
PPP crashes when the number of pointings is larger than 3999 by the limitation of hvplot.

https://github.com/holoviz/holoviews/blob/ad31edadbd1d56e7eb215f36b912ac17ed0e13e2/holoviews/core/util.py#L1158C1-L1171C1

**Expected behavior**
PPP return error message.

**Error output**

```
2023-10-23 10:04:40,166 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p12670'}]]}}}]}
 error: ValueError('Argument must be between 1 and 3999')
Traceback (most recent call last):
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 286, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 245, in handle_event
    event_cls._handle_event(doc, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/events.py", line 280, in _handle_event
    cb(event.msg_data)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 491, in _server_event
    self._comm_event(doc, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 478, in _comm_event
    state._handle_exception(e)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/io/state.py", line 436, in _handle_exception
    raise exception
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 476, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/reactive.py", line 413, in _process_bokeh_event
    self._process_event(event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/widgets/button.py", line 243, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/src/pfs_target_uploader/pn_app.py", line 227, in cb_PPP
    res_mode_, nppc, p_result_fig, p_result_ppc, p_result_tab_ = ppp_result(
                                                                 ^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/src/pfs_target_uploader/utils/ppp.py", line 1180, in ppp_result
    return nppc, p_result_fig, p_result_tab, p_result_ppc

  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/src/pfs_target_uploader/utils/ppp.py", line 1137, in ppp_plotFig
    obj_alloc = obj_allo1[:nppc_fin]
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/layout/base.py", line 782, in __init__
    params['objects'] = [panel(pane) for pane in objects]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/layout/base.py", line 782, in <listcomp>
    params['objects'] = [panel(pane) for pane in objects]
                         ^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/pane/base.py", line 87, in panel
    pane = PaneBase.get_pane_type(obj, **kwargs)(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/param.py", line 788, in __init__
    self._replace_pane()
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/param.py", line 854, in _replace_pane
    new_object = self.eval(self.object)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/param.py", line 813, in eval
    return eval_function(function)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/util/__init__.py", line 328, in eval_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/param/parameterized.py", line 407, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/panel/depends.py", line 249, in wrapped
    return eval_fn()(*combined_args, **combined_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/src/pfs_target_uploader/utils/ppp.py", line 1010, in plot_ppc
    for ii in ppc_coord
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/src/pfs_target_uploader/utils/ppp.py", line 1008, in PFS_FoV_plot
    ppc_tot_plot = [
                ^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/holoviews/core/overlay.py", line 178, in __init__
    super().__init__(items, **params)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/holoviews/core/dimension.py", line 1321, in __init__
    items = self._process_items(items)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/holoviews/core/dimension.py", line 1342, in _process_items
    cls._unpack_paths(vals, items, counts)
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/holoviews/core/dimension.py", line 1395, in _unpack_paths
    new_path = util.make_path_unique(path, counts, new)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/holoviews/core/util.py", line 1907, in make_path_unique
    path = path + (int_to_roman(count),)
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/monodera/Dropbox/NAOJ/PFS/pfs_target_uploader/.venv/lib/python3.11/site-packages/holoviews/core/util.py", line 1162, in int_to_roman
    raise ValueError("Argument must be between 1 and 3999")
ValueError: Argument must be between 1 and 3999
```

**Computer Environment:**
 - OS: macOS Sonoma
 - Browser: Firefox

**Additional context**
It's not realistic, but.

**Comment by monodera** [comment]
I switched to a different library to draw polygons in #117
